spring.application.name=MySpringWeb

#Database configuration
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test
spring.datasource.username=3FfzNWsL2Fdk2Sx.root
spring.datasource.password=mQb0aDkoiROFGpZ9

#JPA Configuration - Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

